// docs/project.md generation. Renders project structure (repos, microservices,
// parents) into a Markdown file consumed by both humans and the cross-repo
// announcement workflow (parent server-repo path lookup).

use crate::db::AppDb;
use std::fs;
use std::path::Path;

/// Generate docs/project.md describing the project's structure.
/// Overwrites existing file on each call (app-owned).
pub fn generate_project_md(db: &AppDb, project_id: i64, repo_root: &Path) -> Result<(), String> {
    let project = db.get_project(project_id).map_err(|e| e.to_string())?;
    let repos = db
        .list_repos_by_project(Some(project_id))
        .map_err(|e| e.to_string())?;
    let ms_ids = db
        .list_project_microservices(project_id)
        .map_err(|e| e.to_string())?;
    let parents = db
        .list_parents_of_microservice(project_id)
        .map_err(|e| e.to_string())?;

    let type_display = match project.project_type.as_str() {
        "microservice" => "⚙ Microservice",
        _ => "📁 Standard",
    };

    let mut md = format!(
        "# {}\n\n{}\n\n**Project type:** {}\n\n",
        project.name,
        project.description.as_deref().unwrap_or(""),
        type_display,
    );

    md.push_str("## Repositories\n\n");
    if repos.is_empty() {
        md.push_str("_No repositories._\n\n");
    } else {
        md.push_str("| Repository | Role | Path | GitHub |\n");
        md.push_str("|------------|------|------|--------|\n");
        for r in &repos {
            let name = r.display_name();
            let role = r.role.as_deref().unwrap_or("—");
            let path = r.local_path.as_deref().unwrap_or("—");
            let gh = if r.github_name.is_some() { "✓" } else { "📁 local" };
            md.push_str(&format!("| {} | {} | {} | {} |\n", name, role, path, gh));
        }
        md.push('\n');
    }

    // B-000013: unified table layout across all three sections — humans see
    // the same shape everywhere, LLMs still grep the same marker strings
    // (`_no local path configured_`, `⚠ server repo not resolvable`).
    md.push_str("## Connected microservices\n\n");
    if ms_ids.is_empty() {
        md.push_str("_No connected microservices._\n\n");
    } else {
        md.push_str("| Microservice | Server repo | Path | GitHub |\n");
        md.push_str("|--------------|-------------|------|--------|\n");
        for ms_id in &ms_ids {
            let ms_proj = db.get_project(*ms_id).map_err(|e| e.to_string())?;
            let (srv_label, path_label, gh_label) = match db.server_repo_of_microservice(*ms_id) {
                Ok(srv) => {
                    let path = srv
                        .local_path
                        .clone()
                        .unwrap_or_else(|| "_no local path configured_".to_string());
                    let gh = if srv.github_name.is_some() { "✓" } else { "📁 local" };
                    (srv.display_name(), path, gh.to_string())
                }
                Err(_) => (
                    "⚠ server repo not resolvable".to_string(),
                    "—".to_string(),
                    "—".to_string(),
                ),
            };
            md.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                ms_proj.name, srv_label, path_label, gh_label
            ));
        }
        md.push('\n');
    }

    md.push_str("## Parent projects\n\n");
    if parents.is_empty() {
        md.push_str("_No parent projects._\n\n");
    } else {
        // F-000040: include each parent server-repo's local path so MS-LLM
        // can write proactive announcements directly into that filesystem.
        // server_repo_of_microservice() is generic over project_id and
        // returns the server-role repo of any project (despite its name).
        md.push_str("| Parent project | Server repo | Path | GitHub |\n");
        md.push_str("|----------------|-------------|------|--------|\n");
        for p in &parents {
            let (srv_label, path_label, gh_label) = match db.server_repo_of_microservice(p.id) {
                Ok(srv) => {
                    let path = srv
                        .local_path
                        .clone()
                        .unwrap_or_else(|| "_no local path configured_".to_string());
                    let gh = if srv.github_name.is_some() { "✓" } else { "📁 local" };
                    (srv.display_name(), path, gh.to_string())
                }
                Err(_) => (
                    "⚠ server repo not resolvable".to_string(),
                    "—".to_string(),
                    "—".to_string(),
                ),
            };
            md.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                p.name, srv_label, path_label, gh_label
            ));
        }
        md.push('\n');
    }

    md.push_str("---\n_Auto-generated by Solo Dev Hub. Do not edit manually — changes will be overwritten on next sync._\n");

    let docs_dir = repo_root.join("docs");
    fs::create_dir_all(&docs_dir).map_err(|e| e.to_string())?;
    fs::write(docs_dir.join("project.md"), md).map_err(|e| e.to_string())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::template_seeder::seed_bundled_templates;
    use std::fs;
    use tempfile::TempDir;

    fn make_test_db() -> AppDb {
        let dir = TempDir::new().unwrap();
        let db = AppDb::new(dir.path().join("test.db")).unwrap();
        seed_bundled_templates(&db).unwrap();
        db
    }

    #[test]
    fn test_generate_project_md_standard_with_repos() {
        let db = make_test_db();
        let proj = db.create_project("WebApp", Some("My web application"), "standard").unwrap();
        let repo = db.upsert_repository("owner/web-backend", None, None, None, None, None).unwrap();
        db.assign_repository(repo.id, Some(proj.id), Some("server")).unwrap();

        let tmp = TempDir::new().unwrap();
        generate_project_md(&db, proj.id, tmp.path()).unwrap();

        let content = fs::read_to_string(tmp.path().join("docs/project.md")).unwrap();
        assert!(content.contains("# WebApp"));
        assert!(content.contains("My web application"));
        assert!(content.contains("📁 Standard"));
        // B-000001: display_name() returns last segment, not full owner/repo.
        assert!(content.contains("web-backend"));
        assert!(!content.contains("owner/web-backend"));
        assert!(content.contains("server"));
    }

    #[test]
    fn test_generate_project_md_microservice_with_parents() {
        let db = make_test_db();
        let parent = db.create_project("Parent", None, "standard").unwrap();
        let ms = db.create_project("AuthMS", None, "microservice").unwrap();
        let ms_repo = db.upsert_repository("owner/auth-backend", None, None, None, None, None).unwrap();
        db.assign_repository(ms_repo.id, Some(ms.id), Some("server")).unwrap();
        db.connect_microservice(parent.id, ms.id).unwrap();

        let tmp = TempDir::new().unwrap();
        generate_project_md(&db, ms.id, tmp.path()).unwrap();

        let content = fs::read_to_string(tmp.path().join("docs/project.md")).unwrap();
        assert!(content.contains("# AuthMS"));
        assert!(content.contains("⚙ Microservice"));
        assert!(content.contains("Parent"), "parent project listed");
    }

    /// F-000040: Parent projects section must include parent server-repo's
    /// local path so MS-LLM can write announcements directly into that filesystem.
    #[test]
    fn test_generate_project_md_microservice_parent_includes_server_path() {
        let db = make_test_db();
        let parent = db.create_project("WebApp", None, "standard").unwrap();
        let parent_srv = db
            .upsert_repository("owner/web-app-backend", None, None, None, None, None)
            .unwrap();
        db.assign_repository(parent_srv.id, Some(parent.id), Some("server"))
            .unwrap();
        db.set_repo_local_path(parent_srv.id, Some("/home/dev/web-app-backend"))
            .unwrap();

        let ms = db.create_project("Storage", None, "microservice").unwrap();
        let ms_repo = db
            .upsert_repository("owner/storage-backend", None, None, None, None, None)
            .unwrap();
        db.assign_repository(ms_repo.id, Some(ms.id), Some("server"))
            .unwrap();
        db.connect_microservice(parent.id, ms.id).unwrap();

        let tmp = TempDir::new().unwrap();
        generate_project_md(&db, ms.id, tmp.path()).unwrap();

        let content = fs::read_to_string(tmp.path().join("docs/project.md")).unwrap();
        // MS-LLM consumes path from this row to write announcements to parent.
        // B-000013: unified table layout — parent row carries server repo + path columns.
        assert!(
            content.contains("| WebApp | web-app-backend | /home/dev/web-app-backend | ✓ |"),
            "parent rendering should include canonical server-repo name + local path in table row; got:\n{}",
            content
        );
    }

    /// F-000040: Parent server repo without local_path renders graceful placeholder
    /// (announcement-write is impossible in that state, but project.md still renders).
    #[test]
    fn test_generate_project_md_microservice_parent_without_server_path() {
        let db = make_test_db();
        let parent = db.create_project("WebApp", None, "standard").unwrap();
        let parent_srv = db
            .upsert_repository("owner/web-app-backend", None, None, None, None, None)
            .unwrap();
        db.assign_repository(parent_srv.id, Some(parent.id), Some("server"))
            .unwrap();
        // intentionally no set_repo_local_path

        let ms = db.create_project("Storage", None, "microservice").unwrap();
        let ms_repo = db
            .upsert_repository("owner/storage-backend", None, None, None, None, None)
            .unwrap();
        db.assign_repository(ms_repo.id, Some(ms.id), Some("server"))
            .unwrap();
        db.connect_microservice(parent.id, ms.id).unwrap();

        let tmp = TempDir::new().unwrap();
        generate_project_md(&db, ms.id, tmp.path()).unwrap();

        let content = fs::read_to_string(tmp.path().join("docs/project.md")).unwrap();
        // B-000013: marker string `_no local path configured_` survives the format
        // change so the announcement-LLM grep stays unchanged.
        assert!(
            content.contains("| WebApp | web-app-backend | _no local path configured_ | ✓ |"),
            "should signal missing path explicitly in table row; got:\n{}",
            content
        );
    }

    #[test]
    fn test_generate_project_md_fallback_placeholders_when_empty() {
        let db = make_test_db();
        let proj = db.create_project("Empty", None, "standard").unwrap();

        let tmp = TempDir::new().unwrap();
        generate_project_md(&db, proj.id, tmp.path()).unwrap();

        let content = fs::read_to_string(tmp.path().join("docs/project.md")).unwrap();
        assert!(content.contains("_No repositories._"));
        assert!(content.contains("_No connected microservices._"));
        assert!(content.contains("_No parent projects._"));
        assert!(!content.contains("{{"));
    }
}
