use crate::models::{DoneTask, FileBugNote, TodoTask};

/// F-026 helper: split by `|` but treat `\|` as an escaped literal pipe.
/// Replacement for naive `str::split('|')` / `splitn(N, '|')` that breaks when
/// a field contains a legit `|` (e.g. regex `/a|b/` in a bug description).
/// Shared across bug-reports, todo and done parsers (all pipe-separated formats).
pub fn split_pipe_respecting_escape(s: &str) -> Vec<String> {
    let mut parts: Vec<String> = Vec::new();
    let mut current = String::new();
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(&next) = chars.peek() {
                if next == '|' {
                    chars.next();
                    current.push('|');
                    continue;
                }
            }
            current.push(c);
        } else if c == '|' {
            parts.push(current.clone());
            current.clear();
        } else {
            current.push(c);
        }
    }
    parts.push(current);
    parts
}

// ── New format: generate / parse ─────────────────────────────────────────────

/// Escape a field value for pipe-separated MD:
///   literal `|` → `\|` (so parser can tell it apart from field separator)
///   literal `\n` → `\\n` (preserve newlines in single-line field)
/// Order matters: pipe first, then newline, so `|` in description with newlines works.
fn escape_field(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', "\\n")
}

/// Reverse `escape_field` on parse: unescape `\n` then `\|`.
fn unescape_field(s: &str) -> String {
    s.replace("\\n", "\n").replace("\\|", "|")
}

/// F-026 v2 format — 8 pipe-separated fields:
/// `id | date | description | severity | category | status | fix_attempts | comment`
/// Generated by the app. Confirmed bugs are excluded by caller.
pub fn generate_bug_reports(bugs: &[FileBugNote]) -> String {
    let mut md = String::new();
    md.push_str("# Bug reports\n\n");
    md.push_str("## Bug workflow\n\n");
    md.push_str("1. **User** creates a bug in the app → status `created`\n");
    md.push_str("2. **Developer/LLM** takes it in progress → status `in-progress`\n");
    md.push_str(
        "3. **Developer/LLM** fixes it and writes a comment on what was done → status `testing` (this transition bumps `fix_attempts` +1)\n",
    );
    md.push_str("4. **User** verifies: ok → status `confirmed` (LLM removes the row on next cleanup pass) / not ok → status `rejected` + comment explaining why\n\n");
    md.push_str("**LLM may edit only `status` and `comment`.** Other fields (description/severity/category) are user-owned; `id`/`date` immutable; `fix_attempts` app-managed.\n\n");
    md.push_str("**LLM must not create new bug rows** — use the app's \"+ Add bug\" button so id/date/DB-stats are wired. To flag a finding, add a `T-NNN` to `todo.md` instead.\n\n");
    md.push_str("**Escape:** a literal `|` inside description/comment is written as `\\|`. A literal newline is `\\n`.\n\n");
    md.push_str("## Open bugs\n\n");
    for bug in bugs {
        let description = escape_field(&bug.description);
        let comment = escape_field(bug.comment.as_deref().unwrap_or(""));
        md.push_str(&format!(
            "- {} | {} | {} | {} | {} | {} | {} | {}\n",
            bug.id,
            bug.date,
            description,
            bug.severity,
            bug.category,
            bug.status,
            bug.fix_attempts,
            comment,
        ));
    }
    md
}

/// Parse bug-reports.md v2 (8 pipe-separated fields). Legacy v1 (10 fields with screen +
/// reproduction) removed in v0.13.9 after user-side migration — all files were re-saved
/// via BugNotes "⬇ v2" button. See `parse_markdown_legacy` for the much older "# Bug List:"
/// pre-pipe format (import-only, unrelated).
pub fn parse_bug_reports(content: &str) -> (Vec<FileBugNote>, Vec<String>) {
    let mut bugs = Vec::new();
    let mut warnings = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        let rest_opt = trimmed.strip_prefix("- [ ] ").or_else(|| {
            trimmed
                .strip_prefix("- ")
                .filter(|r| r.starts_with("B-") || r.starts_with("VB-"))
        });
        let Some(rest) = rest_opt else { continue };
        let parts: Vec<String> = split_pipe_respecting_escape(rest)
            .into_iter()
            .map(|s| s.trim().to_string())
            .collect();

        if parts.len() != 8 {
            warnings.push(format!(
                "Unparseable bug line ({} fields, expected 8): {}",
                parts.len(),
                line
            ));
            continue;
        }
        bugs.push(FileBugNote {
            id: parts[0].clone(),
            date: parts[1].clone(),
            description: unescape_field(&parts[2]),
            severity: parts[3].clone(),
            category: parts[4].clone(),
            status: parts[5].clone(),
            fix_attempts: parts[6].parse::<i32>().unwrap_or(0),
            comment: if parts[7].is_empty() {
                None
            } else {
                Some(unescape_field(&parts[7]))
            },
        });
    }

    (bugs, warnings)
}

// ── Legacy (old-format) import ────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct ParsedHeader {
    pub github_name: String,
}

#[derive(Debug, Clone)]
pub struct ParsedBug {
    #[allow(dead_code)]
    pub id: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub priority: String,
    pub category: String,
    pub is_resolved: bool,
    pub fix_attempts: i32,
    #[allow(dead_code)]
    pub created_at: Option<String>,
    #[allow(dead_code)]
    pub resolved_at: Option<String>,
}

#[derive(Debug)]
pub struct ParsedMarkdown {
    #[allow(dead_code)]
    pub github_name: String,
    pub bugs: Vec<ParsedBug>,
    pub skipped_lines: usize,
}

pub fn parse_header(md: &str) -> Option<ParsedHeader> {
    for line in md.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("# Bug List:") {
            let github_name = rest.trim().to_string();
            if !github_name.is_empty() {
                return Some(ParsedHeader { github_name });
            }
        }
    }
    None
}

pub fn parse_bug_entry(line: &str, desc_lines: &[&str]) -> Option<ParsedBug> {
    let trimmed = line.trim();

    let (is_resolved, rest) = if let Some(r) = trimmed.strip_prefix("- [ ]") {
        (false, r.trim())
    } else if let Some(r) = trimmed.strip_prefix("- [x]") {
        (true, r.trim())
    } else {
        return None;
    };

    let (priority, category, rest) = if let Some(r) = rest.strip_prefix("**[") {
        if let Some(end) = r.find("]**") {
            let inner = &r[..end];
            let after = r[end + 3..].trim();
            if let Some(pipe_pos) = inner.find('|') {
                let priority = inner[..pipe_pos].to_lowercase();
                let category = inner[pipe_pos + 1..].to_lowercase();
                (priority, category, after)
            } else {
                let priority = inner.to_lowercase();
                (priority, "unknown".to_string(), after)
            }
        } else {
            ("medium".to_string(), "unknown".to_string(), rest)
        }
    } else {
        ("medium".to_string(), "unknown".to_string(), rest)
    };

    let id = if let Some(comment_start) = rest.find("<!-- id:") {
        let after = &rest[comment_start + 8..];
        if let Some(comment_end) = after.find(" -->") {
            let raw = after[..comment_end].trim().to_string();
            if raw.is_empty() {
                None
            } else {
                Some(raw)
            }
        } else {
            None
        }
    } else {
        None
    };

    let fix_attempts = if let Some(att_start) = rest.find("[attempts:") {
        let after = &rest[att_start + 10..];
        let trimmed_after = after.trim_start();
        if let Some(att_end) = trimmed_after.find(']') {
            trimmed_after[..att_end].trim().parse::<i32>().unwrap_or(0)
        } else {
            0
        }
    } else {
        0
    };

    let title_end = rest
        .find(" [attempts:")
        .or_else(|| rest.find(" <!-- id:"))
        .unwrap_or(rest.len());
    let title = rest[..title_end].trim().to_string();

    if title.is_empty() {
        return None;
    }

    let mut desc_parts: Vec<String> = Vec::new();
    let mut created_at: Option<String> = None;
    let mut resolved_at: Option<String> = None;

    for desc_line in desc_lines {
        let dl = desc_line.trim();
        if let Some(content) = dl.strip_prefix("> ") {
            if let Some(date) = content.strip_prefix("Created: ") {
                created_at = Some(date.trim().to_string());
            } else if let Some(date) = content.strip_prefix("Resolved: ") {
                resolved_at = Some(date.trim().to_string());
            } else {
                desc_parts.push(content.to_string());
            }
        } else if dl == ">" {
            desc_parts.push(String::new());
        }
    }

    let description = if desc_parts.is_empty() {
        None
    } else {
        Some(desc_parts.join("\n"))
    };

    Some(ParsedBug {
        id,
        title,
        description,
        priority,
        category,
        is_resolved,
        fix_attempts,
        created_at,
        resolved_at,
    })
}

/// Parse legacy "# Bug List:" format markdown.
pub fn parse_markdown_legacy(md: &str) -> Option<ParsedMarkdown> {
    let header = parse_header(md)?;
    let lines: Vec<&str> = md.lines().collect();

    let mut bugs: Vec<ParsedBug> = Vec::new();
    let mut skipped_lines = 0usize;
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim();

        if trimmed.starts_with("- [ ]") || trimmed.starts_with("- [x]") {
            let mut desc_lines: Vec<&str> = Vec::new();
            let mut j = i + 1;
            while j < lines.len() {
                let next = lines[j];
                let next_trimmed = next.trim();
                if next_trimmed.starts_with('>')
                    || (next.starts_with("  ") && !next_trimmed.starts_with("- "))
                {
                    desc_lines.push(next);
                    j += 1;
                } else {
                    break;
                }
            }

            if let Some(bug) = parse_bug_entry(line, &desc_lines) {
                bugs.push(bug);
            } else {
                skipped_lines += 1;
            }

            i = j;
        } else {
            i += 1;
        }
    }

    Some(ParsedMarkdown {
        github_name: header.github_name,
        bugs,
        skipped_lines,
    })
}

// ── F-021 TODO / DONE parsers ────────────────────────────────────────────────

/// Detect YYYY-MM-DD, DD.MM.YYYY or DD/MM/YYYY at trimmed-equal-10 length.
/// Used as an anchor in the done parser so column shift (no id, or extra middle field)
/// doesn't land date-text in the description column.
fn is_date_like(s: &str) -> bool {
    let s = s.trim();
    if s.len() != 10 {
        return false;
    }
    let b = s.as_bytes();
    // YYYY-MM-DD
    if b[4] == b'-' && b[7] == b'-' {
        return b
            .iter()
            .enumerate()
            .all(|(i, c)| matches!(i, 4 | 7) || c.is_ascii_digit());
    }
    // DD.MM.YYYY or DD/MM/YYYY
    if (b[2] == b'.' || b[2] == b'/') && b[5] == b[2] {
        return b
            .iter()
            .enumerate()
            .all(|(i, c)| matches!(i, 2 | 5) || c.is_ascii_digit());
    }
    false
}

/// True if the line's first stripped word could be a task ID we want to accept
/// (`T-…`, `F-…`, `B-…`, `v0…`, or begins with an ASCII digit for generic IDs).
fn looks_like_task_id_start(r: &str) -> bool {
    r.chars().next().map_or(false, |c| {
        c == 'T' || c == 'F' || c == 'B' || c == 'v' || c.is_ascii_digit()
    })
}

/// Parse `docs/todo.md` tasks. Canonical 5 fields: id | description | effort | priority | status.
/// Tolerant: accepts 3–6+ fields. `status` is always the last field; `id` is always the first.
/// With 4 fields: id | description | effort | status (priority empty).
/// With 3 fields: id | description | status (effort and priority empty).
/// With 6+ fields: description = middle slots joined by ` | ` (e.g. when a feature-id prefix
/// widens the line like `T-037 | F-019 | desc | L | must | open`).
pub fn parse_todo_tasks(content: &str) -> (Vec<TodoTask>, Vec<String>) {
    let mut tasks = Vec::new();
    let mut warnings = Vec::new();
    for line in content.lines() {
        let trimmed = line.trim();
        let rest_opt = trimmed
            .strip_prefix("- [ ] ")
            .or_else(|| trimmed.strip_prefix("- ").filter(|r| looks_like_task_id_start(r)));
        let Some(rest) = rest_opt else { continue };
        let parts: Vec<String> = split_pipe_respecting_escape(rest)
            .into_iter()
            .map(|s| s.trim().to_string())
            .collect();
        let n = parts.len();
        if n < 3 {
            warnings.push(format!("Unparseable todo line: {}", line));
            continue;
        }
        let id = parts[0].clone();
        let (description, effort, priority, status, created_at) = match n {
            3 => (
                parts[1].clone().replace("\\n", "\n"),
                String::new(),
                String::new(),
                parts[2].clone(),
                String::new(),
            ),
            4 => (
                parts[1].clone().replace("\\n", "\n"),
                parts[2].clone(),
                String::new(),
                parts[3].clone(),
                String::new(),
            ),
            5 => (
                parts[1].clone().replace("\\n", "\n"),
                parts[2].clone(),
                parts[3].clone(),
                parts[4].clone(),
                String::new(),
            ),
            6 => (
                parts[1].clone().replace("\\n", "\n"),
                parts[2].clone(),
                parts[3].clone(),
                parts[4].clone(),
                parts[5].clone(),
            ),
            _ => {
                // n >= 7: last 4 = effort, priority, status, created_at; middle = description
                let desc_slots = &parts[1..n - 4];
                (
                    desc_slots.join(" | ").replace("\\n", "\n"),
                    parts[n - 4].clone(),
                    parts[n - 3].clone(),
                    parts[n - 2].clone(),
                    parts[n - 1].clone(),
                )
            }
        };
        tasks.push(TodoTask {
            id,
            description,
            effort,
            priority,
            status,
            created_at,
        });
    }
    (tasks, warnings)
}

/// Parse `docs/done.md` (v0.13.9+ format).
///
/// Structure:
/// ```
/// ## 2026-04-21             ← date header; applies to tasks below until next header
/// - D-001 | Task X | v0.13.9
/// -  | Task without id | v0.13.9
/// ```
///
/// Line format (3 pipe-separated fields): `- <id?> | <description> | <version>`.
/// - If `id` is empty → assign `D-NNN` from a per-file counter (in-memory only — file is NOT modified)
/// - Tolerant: accepts 2 fields (description + version) or 3 fields (with id)
/// - `date` is inherited from the nearest preceding `## <date>` section header. If none, empty.
/// - `## <anything>` is scanned for a date-like substring (YYYY-MM-DD / DD.MM.YYYY / DD/MM/YYYY),
///   so legacy headers like `## День 29.03.2026` still produce a date.
///
/// Legacy `- [x] ...` rows (checkbox, 4 fields with `commit`) are NOT supported — user rewrites
/// per-project when migrating. Parser tolerates them by extracting what it can; unparseable lines
/// produce warnings.
pub fn parse_done_tasks(content: &str) -> (Vec<DoneTask>, Vec<String>) {
    let mut tasks = Vec::new();
    let mut warnings = Vec::new();
    let mut current_date = String::new();
    let mut auto_counter: i32 = 0;

    for line in content.lines() {
        let trimmed = line.trim();

        // Section header with date: `## <...date...>`.
        if let Some(rest) = trimmed.strip_prefix("## ") {
            if let Some(d) = rest.split_whitespace().find(|w| is_date_like(w)) {
                current_date = d.trim().to_string();
            }
            continue;
        }

        // Task line: `- ...`. Accept legacy `- [x] ` / `- [X] ` prefixes for transition.
        let rest_opt = trimmed
            .strip_prefix("- [x] ")
            .or_else(|| trimmed.strip_prefix("- [X] "))
            .or_else(|| trimmed.strip_prefix("- "));
        let Some(rest) = rest_opt else { continue };

        let parts: Vec<String> = split_pipe_respecting_escape(rest)
            .into_iter()
            .map(|s| s.trim().to_string())
            .collect();

        let (id_raw, description, version) = match parts.len() {
            // Canonical v0.13.9+ — 3 fields (id slot may be empty but pipes present).
            3 => (parts[0].clone(), parts[1].clone(), parts[2].clone()),
            // Legacy migration tolerance: old `- [x] id | desc | date | commit` (4 fields).
            // Keep id/desc, drop inline date (section-header wins), treat commit as version slot.
            4 => (parts[0].clone(), parts[1].clone(), parts[3].clone()),
            _ => {
                warnings.push(format!(
                    "Unparseable done line ({} fields, expected 3 — id slot may be empty but pipes must be present): {}",
                    parts.len(),
                    line
                ));
                continue;
            }
        };

        let id = if id_raw.is_empty() {
            auto_counter += 1;
            format!("D-{:06}", auto_counter)
        } else {
            id_raw
        };

        tasks.push(DoneTask {
            id,
            description: description.replace("\\n", "\n"),
            date: current_date.clone(),
            version,
        });
    }

    (tasks, warnings)
}

/// Parse docs/done.md and count entries per `## YYYY-MM-DD` section header
/// falling within [start, end] (inclusive). Returns Vec<(date, count)> sorted by date.
/// Missing file → empty vec (not an error).
pub fn parse_done_entries_in_period(
    path: &std::path::Path,
    start: &str,
    end: &str,
) -> std::io::Result<Vec<(String, i64)>> {
    if !path.exists() {
        return Ok(vec![]);
    }
    let content = std::fs::read_to_string(path)?;
    let mut current_date: Option<String> = None;
    let mut counts: std::collections::HashMap<String, i64> = std::collections::HashMap::new();

    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(date_str) = trimmed.strip_prefix("## ") {
            let date = date_str.trim();
            if date.len() == 10
                && chrono::NaiveDate::parse_from_str(date, "%Y-%m-%d").is_ok()
            {
                current_date = Some(date.to_string());
            } else {
                current_date = None;
            }
        } else if trimmed.starts_with("- ") {
            if let Some(d) = &current_date {
                if d.as_str() >= start && d.as_str() <= end {
                    *counts.entry(d.clone()).or_insert(0) += 1;
                }
            }
        }
    }

    let mut out: Vec<(String, i64)> = counts.into_iter().collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_file_bug(
        id: &str,
        date: &str,
        description: &str,
        severity: &str,
        category: &str,
        status: &str,
        comment: Option<&str>,
    ) -> FileBugNote {
        FileBugNote {
            id: id.to_string(),
            date: date.to_string(),
            description: description.to_string(),
            severity: severity.to_string(),
            category: category.to_string(),
            status: status.to_string(),
            fix_attempts: 0,
            comment: comment.map(|s| s.to_string()),
        }
    }

    #[test]
    fn test_parse_header() {
        let md = "# Bug List: owner/repo\n\n**Project:** Test";
        let header = parse_header(md).unwrap();
        assert_eq!(header.github_name, "owner/repo");
    }

    #[test]
    fn test_parse_bug_entry_open() {
        let line = "- [ ] **[CRITICAL|BACKEND]** Bug title [attempts: 2] <!-- id:42 -->";
        let desc = ["  > Description", "  > Created: 2026-03-20"];
        let bug = parse_bug_entry(line, &desc).unwrap();
        assert_eq!(bug.title, "Bug title");
        assert_eq!(bug.priority, "critical");
        assert_eq!(bug.category, "backend");
        assert!(!bug.is_resolved);
        assert_eq!(bug.fix_attempts, 2);
        assert_eq!(bug.id.as_deref(), Some("42"));
        assert_eq!(bug.description.as_deref(), Some("Description"));
        assert_eq!(bug.created_at.as_deref(), Some("2026-03-20"));
    }

    #[test]
    fn test_parse_bug_entry_resolved() {
        let line = "- [x] **[MEDIUM|UI_UX]** Fixed bug [attempts: 1] <!-- id:41 -->";
        let desc = ["  > Was broken", "  > Resolved: 2026-03-18"];
        let bug = parse_bug_entry(line, &desc).unwrap();
        assert_eq!(bug.title, "Fixed bug");
        assert_eq!(bug.priority, "medium");
        assert_eq!(bug.category, "ui_ux");
        assert!(bug.is_resolved);
        assert_eq!(bug.fix_attempts, 1);
        assert_eq!(bug.id.as_deref(), Some("41"));
        assert_eq!(bug.resolved_at.as_deref(), Some("2026-03-18"));
    }

    #[test]
    fn test_parse_bug_entry_no_id() {
        let line = "- [ ] **[LOW]** No id bug [attempts: 0]";
        let bug = parse_bug_entry(line, &[]).unwrap();
        assert_eq!(bug.title, "No id bug");
        assert_eq!(bug.category, "unknown");
        assert_eq!(bug.id, None);
        assert_eq!(bug.fix_attempts, 0);
    }

    #[test]
    fn test_parse_full_markdown() {
        let md = r#"# Bug List: owner/repo

**Project:** My Project
**Role:** server
**Exported:** 2026-03-28

## Open Bugs (1)

- [ ] **[CRITICAL|BACKEND]** Bug title [attempts: 2] <!-- id:42 -->
  > Description
  > Created: 2026-03-20

## Resolved Bugs (1)

- [x] **[MEDIUM|UI_UX]** Fixed bug [attempts: 1] <!-- id:41 -->
  > Was broken
  > Resolved: 2026-03-18
"#;
        let parsed = parse_markdown_legacy(md).unwrap();
        assert_eq!(parsed.github_name, "owner/repo");
        assert_eq!(parsed.bugs.len(), 2);

        let open = parsed.bugs.iter().find(|b| !b.is_resolved).unwrap();
        assert_eq!(open.title, "Bug title");
        assert_eq!(open.id.as_deref(), Some("42"));

        let resolved = parsed.bugs.iter().find(|b| b.is_resolved).unwrap();
        assert_eq!(resolved.title, "Fixed bug");
        assert_eq!(resolved.id.as_deref(), Some("41"));
    }

    // ── New format tests ──────────────────────────────────────────────────────

    #[test]
    fn test_generate_v2_format() {
        let bugs = vec![make_file_bug(
            "B-001",
            "2026-03-29",
            "App crashes on login",
            "major",
            "auth",
            "open",
            None,
        )];
        let md = generate_bug_reports(&bugs);
        assert!(md.contains("# Bug reports"));
        assert!(md.contains("## Open bugs"));
        assert!(md.contains("B-001 | 2026-03-29 | App crashes on login | major | auth | open | 0 |"));
    }

    #[test]
    fn test_parse_v2_format() {
        let md = "# Bug reports\n\n## Open bugs\n\n- B-001 | 2026-03-29 | App crashes | major | auth | open | 2 | Needs fix\n";
        let (bugs, warnings) = parse_bug_reports(md);
        assert_eq!(bugs.len(), 1);
        assert!(warnings.is_empty());
        let b = &bugs[0];
        assert_eq!(b.id, "B-001");
        assert_eq!(b.description, "App crashes");
        assert_eq!(b.severity, "major");
        assert_eq!(b.fix_attempts, 2);
        assert_eq!(b.comment.as_deref(), Some("Needs fix"));
    }

    #[test]
    fn test_legacy_v1_10_fields_rejected_as_warning() {
        // v1 legacy 10-field format is no longer supported (v0.13.9).
        // Parser must emit a warning and skip the line instead of silently merging fields.
        let md = "- B-001 | 2026-03-29 | LoginScreen | App crashes | Tap Login | major | auth | open | 1 | note\n";
        let (bugs, warnings) = parse_bug_reports(md);
        assert_eq!(bugs.len(), 0);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("10 fields"));
    }

    #[test]
    fn test_roundtrip_v2() {
        let original = vec![
            make_file_bug("B-001", "2026-03-29", "Crash", "critical", "ui", "open", Some("Needs fix")),
            make_file_bug("B-002", "2026-03-28", "Layout broken", "minor", "ui", "in-progress", None),
        ];
        let md = generate_bug_reports(&original);
        let (parsed, warnings) = parse_bug_reports(&md);
        assert!(warnings.is_empty());
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].id, "B-001");
        assert_eq!(parsed[0].description, "Crash");
        assert_eq!(parsed[0].comment.as_deref(), Some("Needs fix"));
        assert_eq!(parsed[1].id, "B-002");
        assert!(parsed[1].comment.is_none());
    }

    #[test]
    fn test_roundtrip_pipe_in_description() {
        // F-026: `|` inside description must survive a generate/parse roundtrip.
        let original = vec![make_file_bug(
            "B-042",
            "2026-04-19",
            "Regex /error|warning/ breaks log parser",
            "major",
            "logic",
            "open",
            None,
        )];
        let md = generate_bug_reports(&original);
        assert!(md.contains(r"/error\|warning/"), "generate must escape | as \\|");
        let (parsed, warnings) = parse_bug_reports(&md);
        assert!(warnings.is_empty());
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].description, "Regex /error|warning/ breaks log parser");
    }

    #[test]
    fn test_confirmed_included() {
        let bugs = vec![
            make_file_bug("B-001", "2026-03-29", "Open bug", "major", "c", "open", None),
            make_file_bug("B-002", "2026-03-29", "Confirmed bug", "minor", "c", "confirmed", None),
        ];
        let md = generate_bug_reports(&bugs);
        assert!(md.contains("B-001"));
        assert!(md.contains("B-002"));
        assert!(md.contains("Confirmed bug"));
    }

    #[test]
    fn test_parse_legacy() {
        let md = r#"# Bug List: owner/repo

## Open Bugs (1)

- [ ] **[HIGH|BACKEND]** Login crash [attempts: 1] <!-- id:10 -->
  > Crash on login page
  > Created: 2026-03-01

## Resolved Bugs (0)

"#;
        let parsed = parse_markdown_legacy(md).unwrap();
        assert_eq!(parsed.bugs.len(), 1);
        let b = &parsed.bugs[0];
        assert_eq!(b.title, "Login crash");
        assert_eq!(b.priority, "high");
        assert_eq!(b.category, "backend");
        assert!(!b.is_resolved);
        assert_eq!(b.id.as_deref(), Some("10"));
    }

    // ── F-021 TODO / DONE parser tests ────────────────────────────────────────

    #[test]
    fn test_parse_todo_valid() {
        let md = "# Tasks\n\n- [ ] T-001 | Add feature X | M | must | open\n- T-002 | Refactor Y | L | should | in-progress\n";
        let (tasks, warnings) = parse_todo_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].id, "T-001");
        assert_eq!(tasks[0].description, "Add feature X");
        assert_eq!(tasks[0].effort, "M");
        assert_eq!(tasks[0].priority, "must");
        assert_eq!(tasks[0].status, "open");
        assert_eq!(tasks[1].status, "in-progress");
    }

    #[test]
    fn test_parse_todo_empty_and_malformed() {
        let md = "# Tasks\n\n(no tasks yet)\n- [ ] only two fields\n- [ ] T-005 | Enough fields | S | could | open\n";
        let (tasks, warnings) = parse_todo_tasks(md);
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T-005");
        assert_eq!(warnings.len(), 1, "malformed line should yield one warning");
    }

    #[test]
    fn test_parse_done_v2_section_header_date() {
        let md = "# Done\n\n## 2026-04-21\n- T-001 | Add feature X | v0.13.9\n- T-002 | Bump deps | v0.13.9\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].id, "T-001");
        assert_eq!(tasks[0].date, "2026-04-21");
        assert_eq!(tasks[0].version, "v0.13.9");
        assert_eq!(tasks[1].id, "T-002");
        assert_eq!(tasks[1].date, "2026-04-21");
    }

    #[test]
    fn test_parse_done_auto_id_when_empty() {
        // Empty id slot (just `-  | desc | version`) → D-000001, D-000002 assigned sequentially (6-digit).
        let md = "## 2026-04-21\n-  | Task without id | v0.13.9\n-  | Another | v0.13.9\n- T-001 | Has id | v0.13.9\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 3);
        assert_eq!(tasks[0].id, "D-000001");
        assert_eq!(tasks[1].id, "D-000002");
        assert_eq!(tasks[2].id, "T-001", "explicit legacy 3-digit id kept untouched");
    }

    #[test]
    fn test_parse_done_two_fields_rejected() {
        // Post v0.13.13: 2-field lines are rejected (must be 3 fields, id slot may be empty
        // but the pipes must be present — contract-wise one shape, not two).
        let md = "## 2026-04-21\n- Quick fix | v0.13.9\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert_eq!(tasks.len(), 0);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("expected 3"));
    }

    #[test]
    fn test_parse_done_three_fields_empty_id_accepted() {
        // Canonical 3-field form with empty id slot — still works, gets D-NNNNNN (6-digit).
        let md = "## 2026-04-21\n- | Quick fix | v0.13.9\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty());
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "D-000001");
        assert_eq!(tasks[0].description, "Quick fix");
        assert_eq!(tasks[0].version, "v0.13.9");
    }

    // v0.20.1: id length-leniency tests — parser must accept both legacy 3-digit
    // (T-001 / B-042 / D-001) and new 6-digit zero-padded (T-000001 / etc) IDs.
    #[test]
    fn test_parse_todo_accepts_legacy_3_digit_id() {
        let input = "- [ ] T-001 | Legacy task | 2 | high | open | 2026-04-26\n";
        let (tasks, warnings) = parse_todo_tasks(input);
        assert!(warnings.is_empty());
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T-001");
    }

    #[test]
    fn test_parse_todo_accepts_new_6_digit_id() {
        let input = "- [ ] T-000042 | New task | 2 | high | open | 2026-04-26\n";
        let (tasks, warnings) = parse_todo_tasks(input);
        assert!(warnings.is_empty());
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T-000042");
    }

    #[test]
    fn test_parse_todo_mixed_id_lengths() {
        // 3-digit + 4-digit + 6-digit + F-prefix all coexist.
        let input = "- [ ] T-001 | Legacy | 1 | low | open | 2026-04-20\n\
                     - [ ] T-1234 | 4-digit transitional | 2 | medium | open | 2026-04-21\n\
                     - [ ] T-000042 | 6-digit new | 4 | high | review | 2026-04-26\n\
                     - [ ] F-000007 | feature 6-digit | 8 | high | open | 2026-04-26\n";
        let (tasks, warnings) = parse_todo_tasks(input);
        assert!(warnings.is_empty());
        assert_eq!(tasks.len(), 4);
        assert_eq!(tasks[0].id, "T-001");
        assert_eq!(tasks[1].id, "T-1234");
        assert_eq!(tasks[2].id, "T-000042");
        assert_eq!(tasks[3].id, "F-000007");
    }

    #[test]
    fn test_parse_done_accepts_legacy_3_digit_id() {
        let md = "## 2026-04-26\n- T-045 | Fix login regression | v0.13.9\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T-045");
    }

    #[test]
    fn test_parse_done_accepts_new_6_digit_id() {
        let md = "## 2026-04-26\n- T-000045 | Fix login regression | v0.20.0\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T-000045");
    }

    #[test]
    fn test_parse_done_mixed_legacy_and_new_id_lengths() {
        let md = "## 2026-04-26\n\
                  - D-007 | legacy 3-digit | v0.18.0\n\
                  - T-000045 | new 6-digit | v0.20.0\n\
                  - F-000013 | feature | v0.20.0\n\
                  -  | empty slot synth | v0.20.0\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 4);
        assert_eq!(tasks[0].id, "D-007");
        assert_eq!(tasks[1].id, "T-000045");
        assert_eq!(tasks[2].id, "F-000013");
        assert_eq!(tasks[3].id, "D-000001", "synth uses 6-digit");
    }

    #[test]
    fn test_parse_done_legacy_header_extracts_date() {
        // Legacy headers like `## День 29.03.2026` still produce a date (anywhere in header).
        let md = "## День 29.03.2026\n- T-001 | Old entry | v0.1.0\n";
        let (tasks, warnings) = parse_done_tasks(md);
        assert!(warnings.is_empty());
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].date, "29.03.2026");
    }

    #[test]
    fn test_parse_done_no_section_header() {
        // Tasks without a preceding `## date` → date is empty.
        let md = "- T-001 | Orphan | v0.1.0\n";
        let (tasks, _warnings) = parse_done_tasks(md);
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].date, "");
    }

    #[test]
    fn test_parse_todo_tolerant_4_and_6_fields() {
        // 4 fields: id | description | effort | status (priority empty)
        // 6 fields (new canonical): id | description | effort | priority | status | created_at
        let md = "- [ ] T-010 | Short task | S | open\n- [ ] T-037 | Full rebrand package | L | must | open | 2026-04-26\n";
        let (tasks, warnings) = parse_todo_tasks(md);
        assert!(warnings.is_empty(), "got warnings: {:?}", warnings);
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].id, "T-010");
        assert_eq!(tasks[0].effort, "S");
        assert_eq!(tasks[0].status, "open");
        assert_eq!(tasks[0].priority, "");
        assert_eq!(tasks[1].id, "T-037");
        assert_eq!(tasks[1].description, "Full rebrand package");
        assert_eq!(tasks[1].effort, "L");
        assert_eq!(tasks[1].priority, "must");
        assert_eq!(tasks[1].status, "open");
        assert_eq!(tasks[1].created_at, "2026-04-26");
    }


    /// B-002 retry#4: regression против реального `docs/done.md` этого репо.
    /// Парсер не должен panic'ить, hang'ить или возвращать нереальные результаты
    /// на фактическом файле пользователя (134 строки, смесь форматов: с id и без,
    /// с commit и без, кириллица, старые секционные заголовки `## День DD.MM.YYYY`).
    #[test]
    fn test_parse_done_real_file_does_not_panic() {
        let content = include_str!("../../docs/done.md");
        let (tasks, warnings) = parse_done_tasks(content);
        eprintln!("done.md stats: {} tasks, {} warnings", tasks.len(), warnings.len());
        if let Some(first) = tasks.first() {
            eprintln!("first task id={:?} desc={:?} date={:?} version={:?}",
                first.id, first.description, first.date, first.version);
        }
        if let Some(last) = tasks.last() {
            eprintln!("last task id={:?} desc={:?} date={:?} version={:?}",
                last.id, last.description, last.date, last.version);
        }
        assert!(tasks.len() + warnings.len() > 0);
    }

    #[test]
    fn test_parse_todo_real_file_does_not_panic() {
        let content = include_str!("../../docs/todo.md");
        let (tasks, warnings) = parse_todo_tasks(content);
        assert!(tasks.len() + warnings.len() > 0);
    }

    /// B-002 retry#4: repro сериализации ReadDoneResult точь-в-точь как в Tauri IPC.
    /// Если serde_json упадёт — это корень зависания (panic в command'е Tauri иногда
    /// не пробрасывается в promise reject, а IPC-канал висит).
    #[test]
    fn test_serialize_done_real_file_to_json() {
        use crate::models::ReadDoneResult;
        let content = include_str!("../../docs/done.md");
        let (tasks, warnings) = parse_done_tasks(content);
        let result = ReadDoneResult { tasks, warnings };
        let json = serde_json::to_string(&result).expect("serde must not fail");
        eprintln!("JSON size: {} bytes", json.len());
        assert!(json.len() > 0);
    }

    #[test]
    fn test_is_date_like() {
        assert!(is_date_like("2026-04-19"));
        assert!(is_date_like("19.04.2026"));
        assert!(is_date_like("19/04/2026"));
        assert!(!is_date_like("Hello world"));
        assert!(!is_date_like("2026-4-19"));
        assert!(!is_date_like("20260419")); // length-mismatch
    }

    #[test]
    fn test_split_pipe_respecting_escape() {
        let parts = split_pipe_respecting_escape("a | b\\|c | d");
        assert_eq!(parts.len(), 3);
        assert_eq!(parts[0].trim(), "a");
        assert_eq!(parts[1].trim(), "b|c");
        assert_eq!(parts[2].trim(), "d");
    }

    #[test]
    fn test_parse_done_entries_in_period_counts_per_day() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("done.md");
        std::fs::write(
            &path,
            "# Done\n\n\
             ## 2026-04-20\n\
             - T-001 | First task | v0.1\n\
             - T-002 | Second task | v0.1\n\n\
             ## 2026-04-22\n\
             - T-003 | Third | v0.2\n\n\
             ## 2026-04-25\n\
             - T-004 | Outside period | v0.3\n",
        ).unwrap();

        let result = parse_done_entries_in_period(&path, "2026-04-20", "2026-04-24").unwrap();
        // Expected: 2026-04-20 -> 2, 2026-04-22 -> 1, others omitted
        assert_eq!(result.len(), 2);
        let map: std::collections::HashMap<String, i64> = result.into_iter().collect();
        assert_eq!(map.get("2026-04-20"), Some(&2));
        assert_eq!(map.get("2026-04-22"), Some(&1));
        assert!(!map.contains_key("2026-04-25"));
    }

    #[test]
    fn test_parse_done_entries_missing_file_returns_empty() {
        let r = parse_done_entries_in_period(
            std::path::Path::new("/no/such/file.md"),
            "2026-04-01",
            "2026-04-30",
        ).unwrap();
        assert!(r.is_empty());
    }

    #[test]
    fn test_parse_todo_6_fields_new_format() {
        let input = "- [ ] T-042 | Add Go deploy template | 4 | high | open | 2026-04-26\n";
        let (tasks, warnings) = parse_todo_tasks(input);
        assert!(warnings.is_empty(), "no warnings for valid 6-field");
        assert_eq!(tasks.len(), 1);
        let t = &tasks[0];
        assert_eq!(t.id, "T-042");
        assert_eq!(t.description, "Add Go deploy template");
        assert_eq!(t.effort, "4");
        assert_eq!(t.priority, "high");
        assert_eq!(t.status, "open");
        assert_eq!(t.created_at, "2026-04-26");
    }

    #[test]
    fn test_parse_todo_5_fields_legacy_empty_created_at() {
        let input = "- [ ] T-001 | Legacy task | 2 | medium | open\n";
        let (tasks, _) = parse_todo_tasks(input);
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].created_at, "");
        assert_eq!(tasks[0].status, "open");
    }

    #[test]
    fn test_parse_todo_mixed_5_and_6_field_lines() {
        let input = "- [ ] T-001 | Legacy task | 2 | medium | open\n- [ ] T-002 | New task | 4 | high | review | 2026-04-26\n";
        let (tasks, _) = parse_todo_tasks(input);
        assert_eq!(tasks.len(), 2);
        assert_eq!(tasks[0].created_at, "");
        assert_eq!(tasks[1].created_at, "2026-04-26");
    }

    #[test]
    fn test_parse_todo_7_or_more_fields_joined_into_description() {
        let input = "- [ ] T-001 | Multi pipe \\| not escaped | wat | 4 | high | open | 2026-04-26\n";
        let (tasks, _) = parse_todo_tasks(input);
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, "T-001");
        assert_eq!(tasks[0].effort, "4");
        assert_eq!(tasks[0].priority, "high");
        assert_eq!(tasks[0].status, "open");
        assert_eq!(tasks[0].created_at, "2026-04-26");
    }
}
