use crate::models::FileBugNote;

use super::util::{escape_field, split_pipe_respecting_escape, unescape_field};

// ── New format: generate / parse ─────────────────────────────────────────────

/// F-026 v2 format — 8 pipe-separated fields:
/// `id | date | description | severity | category | status | fix_attempts | comment`
/// Generated by the app. Confirmed bugs are excluded by caller.
pub fn generate_bug_reports(bugs: &[FileBugNote]) -> String {
    let mut md = String::new();
    md.push_str("# Bug reports\n\n");
    md.push_str("## Bug workflow\n\n");
    md.push_str("1. **User** creates a bug in the app → status `created`\n");
    md.push_str("2. **Developer/LLM** takes it in progress → status `in-progress`\n");
    md.push_str(
        "3. **Developer/LLM** fixes it and writes a comment on what was done → status `testing` (this transition bumps `fix_attempts` +1)\n",
    );
    md.push_str("4. **User** verifies: ok → status `confirmed` (LLM removes the row on next cleanup pass) / not ok → status `rejected` + comment explaining why\n\n");
    md.push_str("**LLM may edit only `status` and `comment`.** Other fields (description/severity/category) are user-owned; `id`/`date` immutable; `fix_attempts` app-managed.\n\n");
    md.push_str("**LLM must not create new bug rows** — use the app's \"+ Add bug\" button so id/date/DB-stats are wired. To flag a finding, add a `T-NNN` to `todo.md` instead.\n\n");
    md.push_str("**Escape:** a literal `|` inside description/comment is written as `\\|`. A literal newline is `\\n`.\n\n");
    md.push_str("## Open bugs\n\n");
    for bug in bugs {
        let description = escape_field(&bug.description);
        let comment = escape_field(bug.comment.as_deref().unwrap_or(""));
        md.push_str(&format!(
            "- {} | {} | {} | {} | {} | {} | {} | {}\n",
            bug.id,
            bug.date,
            description,
            bug.severity,
            bug.category,
            bug.status,
            bug.fix_attempts,
            comment,
        ));
    }
    md
}

/// Parse bug-reports.md v2 (8 pipe-separated fields). Legacy v1 (10 fields with screen +
/// reproduction) removed in v0.13.9 after user-side migration — all files were re-saved
/// via BugNotes "⬇ v2" button. See `parse_markdown_legacy` for the much older "# Bug List:"
/// pre-pipe format (import-only, unrelated).
pub fn parse_bug_reports(content: &str) -> (Vec<FileBugNote>, Vec<String>) {
    let mut bugs = Vec::new();
    let mut warnings = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        let rest_opt = trimmed.strip_prefix("- [ ] ").or_else(|| {
            trimmed
                .strip_prefix("- ")
                .filter(|r| r.starts_with("B-") || r.starts_with("VB-"))
        });
        let Some(rest) = rest_opt else { continue };
        let parts: Vec<String> = split_pipe_respecting_escape(rest)
            .into_iter()
            .map(|s| s.trim().to_string())
            .collect();

        if parts.len() != 8 {
            warnings.push(format!(
                "Unparseable bug line ({} fields, expected 8): {}",
                parts.len(),
                line
            ));
            continue;
        }
        bugs.push(FileBugNote {
            id: parts[0].clone(),
            date: parts[1].clone(),
            description: unescape_field(&parts[2]),
            severity: parts[3].clone(),
            category: parts[4].clone(),
            status: parts[5].clone(),
            fix_attempts: parts[6].parse::<i32>().unwrap_or(0),
            comment: if parts[7].is_empty() {
                None
            } else {
                Some(unescape_field(&parts[7]))
            },
        });
    }

    (bugs, warnings)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_file_bug(
        id: &str,
        date: &str,
        description: &str,
        severity: &str,
        category: &str,
        status: &str,
        comment: Option<&str>,
    ) -> FileBugNote {
        FileBugNote {
            id: id.to_string(),
            date: date.to_string(),
            description: description.to_string(),
            severity: severity.to_string(),
            category: category.to_string(),
            status: status.to_string(),
            fix_attempts: 0,
            comment: comment.map(|s| s.to_string()),
        }
    }

    #[test]
    fn test_generate_v2_format() {
        let bugs = vec![make_file_bug(
            "B-001",
            "2026-03-29",
            "App crashes on login",
            "major",
            "auth",
            "open",
            None,
        )];
        let md = generate_bug_reports(&bugs);
        assert!(md.contains("# Bug reports"));
        assert!(md.contains("## Open bugs"));
        assert!(
            md.contains("B-001 | 2026-03-29 | App crashes on login | major | auth | open | 0 |")
        );
    }

    #[test]
    fn test_parse_v2_format() {
        let md = "# Bug reports\n\n## Open bugs\n\n- B-001 | 2026-03-29 | App crashes | major | auth | open | 2 | Needs fix\n";
        let (bugs, warnings) = parse_bug_reports(md);
        assert_eq!(bugs.len(), 1);
        assert!(warnings.is_empty());
        let b = &bugs[0];
        assert_eq!(b.id, "B-001");
        assert_eq!(b.description, "App crashes");
        assert_eq!(b.severity, "major");
        assert_eq!(b.fix_attempts, 2);
        assert_eq!(b.comment.as_deref(), Some("Needs fix"));
    }

    #[test]
    fn test_legacy_v1_10_fields_rejected_as_warning() {
        // v1 legacy 10-field format is no longer supported (v0.13.9).
        // Parser must emit a warning and skip the line instead of silently merging fields.
        let md = "- B-001 | 2026-03-29 | LoginScreen | App crashes | Tap Login | major | auth | open | 1 | note\n";
        let (bugs, warnings) = parse_bug_reports(md);
        assert_eq!(bugs.len(), 0);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("10 fields"));
    }

    #[test]
    fn test_roundtrip_v2() {
        let original = vec![
            make_file_bug(
                "B-001",
                "2026-03-29",
                "Crash",
                "critical",
                "ui",
                "open",
                Some("Needs fix"),
            ),
            make_file_bug(
                "B-002",
                "2026-03-28",
                "Layout broken",
                "minor",
                "ui",
                "in-progress",
                None,
            ),
        ];
        let md = generate_bug_reports(&original);
        let (parsed, warnings) = parse_bug_reports(&md);
        assert!(warnings.is_empty());
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].id, "B-001");
        assert_eq!(parsed[0].description, "Crash");
        assert_eq!(parsed[0].comment.as_deref(), Some("Needs fix"));
        assert_eq!(parsed[1].id, "B-002");
        assert!(parsed[1].comment.is_none());
    }

    #[test]
    fn test_roundtrip_pipe_in_description() {
        // F-026: `|` inside description must survive a generate/parse roundtrip.
        let original = vec![make_file_bug(
            "B-042",
            "2026-04-19",
            "Regex /error|warning/ breaks log parser",
            "major",
            "logic",
            "open",
            None,
        )];
        let md = generate_bug_reports(&original);
        assert!(
            md.contains(r"/error\|warning/"),
            "generate must escape | as \\|"
        );
        let (parsed, warnings) = parse_bug_reports(&md);
        assert!(warnings.is_empty());
        assert_eq!(parsed.len(), 1);
        assert_eq!(
            parsed[0].description,
            "Regex /error|warning/ breaks log parser"
        );
    }

    #[test]
    fn test_confirmed_included() {
        let bugs = vec![
            make_file_bug(
                "B-001",
                "2026-03-29",
                "Open bug",
                "major",
                "c",
                "open",
                None,
            ),
            make_file_bug(
                "B-002",
                "2026-03-29",
                "Confirmed bug",
                "minor",
                "c",
                "confirmed",
                None,
            ),
        ];
        let md = generate_bug_reports(&bugs);
        assert!(md.contains("B-001"));
        assert!(md.contains("B-002"));
        assert!(md.contains("Confirmed bug"));
    }
}
